"""Mapping of GBD etiologies.

This code is automatically generated by gbd_mapping_generator/etiology_builder.py

Any manual changes will be lost.
"""
from .id import reiid
from .etiology_template import Etiology, Etiologies


etiologies = Etiologies(
    cholera=Etiology(
        name='cholera',
        gbd_id=reiid(173),
    ),
    other_salmonella_infections=Etiology(
        name='other_salmonella_infections',
        gbd_id=reiid(174),
    ),
    shigellosis=Etiology(
        name='shigellosis',
        gbd_id=reiid(175),
    ),
    enteropathogenic_e_coli_infection=Etiology(
        name='enteropathogenic_e_coli_infection',
        gbd_id=reiid(176),
    ),
    enterotoxigenic_e_coli_infection=Etiology(
        name='enterotoxigenic_e_coli_infection',
        gbd_id=reiid(177),
    ),
    campylobacter_enteritis=Etiology(
        name='campylobacter_enteritis',
        gbd_id=reiid(178),
    ),
    amoebiasis=Etiology(
        name='amoebiasis',
        gbd_id=reiid(179),
    ),
    cryptosporidiosis=Etiology(
        name='cryptosporidiosis',
        gbd_id=reiid(180),
    ),
    rotaviral_enteritis=Etiology(
        name='rotaviral_enteritis',
        gbd_id=reiid(181),
    ),
    aeromonas=Etiology(
        name='aeromonas',
        gbd_id=reiid(182),
    ),
    clostridium_difficile=Etiology(
        name='clostridium_difficile',
        gbd_id=reiid(183),
    ),
    norovirus=Etiology(
        name='norovirus',
        gbd_id=reiid(184),
    ),
    adenovirus=Etiology(
        name='adenovirus',
        gbd_id=reiid(185),
    ),
    influenza=Etiology(
        name='influenza',
        gbd_id=reiid(187),
    ),
    pneumococcal_pneumonia=Etiology(
        name='pneumococcal_pneumonia',
        gbd_id=reiid(188),
    ),
    h_influenzae_type_b_pneumonia=Etiology(
        name='h_influenzae_type_b_pneumonia',
        gbd_id=reiid(189),
    ),
    respiratory_syncytial_virus_pneumonia=Etiology(
        name='respiratory_syncytial_virus_pneumonia',
        gbd_id=reiid(190),
    ),
)
