"""Mapping of GBD etiologies.

This code is automatically generated by gbd_mapping_generator/etiology_builder.py

Any manual changes will be lost.
"""
from .id import rei_id
from .etiology_template import Etiology, Etiologies


etiologies = Etiologies(
    cholera=Etiology(
        name='cholera',
        kind='etiology',
        gbd_id=rei_id(173),
    ),
    non_typhoidal_salmonella=Etiology(
        name='non_typhoidal_salmonella',
        kind='etiology',
        gbd_id=rei_id(174),
    ),
    shigella=Etiology(
        name='shigella',
        kind='etiology',
        gbd_id=rei_id(175),
    ),
    enteropathogenic_e_coli=Etiology(
        name='enteropathogenic_e_coli',
        kind='etiology',
        gbd_id=rei_id(176),
    ),
    enterotoxigenic_e_coli=Etiology(
        name='enterotoxigenic_e_coli',
        kind='etiology',
        gbd_id=rei_id(177),
    ),
    campylobacter=Etiology(
        name='campylobacter',
        kind='etiology',
        gbd_id=rei_id(178),
    ),
    entamoeba=Etiology(
        name='entamoeba',
        kind='etiology',
        gbd_id=rei_id(179),
    ),
    cryptosporidium=Etiology(
        name='cryptosporidium',
        kind='etiology',
        gbd_id=rei_id(180),
    ),
    rotavirus=Etiology(
        name='rotavirus',
        kind='etiology',
        gbd_id=rei_id(181),
    ),
    aeromonas=Etiology(
        name='aeromonas',
        kind='etiology',
        gbd_id=rei_id(182),
    ),
    clostridium_difficile=Etiology(
        name='clostridium_difficile',
        kind='etiology',
        gbd_id=rei_id(183),
    ),
    norovirus=Etiology(
        name='norovirus',
        kind='etiology',
        gbd_id=rei_id(184),
    ),
    adenovirus=Etiology(
        name='adenovirus',
        kind='etiology',
        gbd_id=rei_id(185),
    ),
    influenza=Etiology(
        name='influenza',
        kind='etiology',
        gbd_id=rei_id(187),
    ),
    pneumococcus=Etiology(
        name='pneumococcus',
        kind='etiology',
        gbd_id=rei_id(188),
    ),
    h_influenzae_type_b=Etiology(
        name='h_influenzae_type_b',
        kind='etiology',
        gbd_id=rei_id(189),
    ),
    respiratory_syncytial_virus=Etiology(
        name='respiratory_syncytial_virus',
        kind='etiology',
        gbd_id=rei_id(190),
    ),
    meningococcal_meningitis=Etiology(
        name='meningococcal_meningitis',
        kind='etiology',
        gbd_id=rei_id(386),
    ),
)
