# -----------------------------------------------------------------------------
#   - invoked on push, pull_request, manual trigger, or schedule
#   - test under at least 3 versions of python
# -----------------------------------------------------------------------------
name: build
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
  
jobs:
  call_build:
    uses: 
      ihmeuw/vivarium_build_utils/.github/workflows/build.yml@add-install-arg
    with:
      # FIXME: We can't clone gbd access but the install branch script should handle that
      dependencies: "vivarium_gbd_access"
      use_mypy: false
      install_type: "test,docs"
