# -----------------------------------------------------------------------------
#   - invoked on push, pull_request, manual trigger, or schedule
#   - test under at least 3 versions of python
# -----------------------------------------------------------------------------
name: build
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
  
jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    uses: 
      ihmeuw/vivarium_build_utils/.github/workflows/build.yml@main
    with:
      # FIXME: We can't clone gbd access but the install branch script should handle that
      dependencies: "vivarium_gbd_access"
      skip_mypy: true
      install_type: "[test,docs]"
    secrets:
      NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
      NOTIFY_PASSWORD: ${{ secrets.NOTIFY_PASSWORD }}
